
package it.uniroma2.sapr.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SAPRDroniService", targetNamespace = "http://service.sapr.uniroma2.it/", wsdlLocation = "http://localhost:9999/ws/sapr?wsdl")
public class SAPRDroniService
    extends Service
{

    private final static URL SAPRDRONISERVICE_WSDL_LOCATION;
    private final static WebServiceException SAPRDRONISERVICE_EXCEPTION;
    private final static QName SAPRDRONISERVICE_QNAME = new QName("http://service.sapr.uniroma2.it/", "SAPRDroniService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/ws/sapr?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SAPRDRONISERVICE_WSDL_LOCATION = url;
        SAPRDRONISERVICE_EXCEPTION = e;
    }

    public SAPRDroniService() {
        super(__getWsdlLocation(), SAPRDRONISERVICE_QNAME);
    }

    public SAPRDroniService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SAPRDRONISERVICE_QNAME, features);
    }

    public SAPRDroniService(URL wsdlLocation) {
        super(wsdlLocation, SAPRDRONISERVICE_QNAME);
    }

    public SAPRDroniService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SAPRDRONISERVICE_QNAME, features);
    }

    public SAPRDroniService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SAPRDroniService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SAPRDroniInterface
     */
    @WebEndpoint(name = "SAPRDroniPort")
    public SAPRDroniInterface getSAPRDroniPort() {
        return super.getPort(new QName("http://service.sapr.uniroma2.it/", "SAPRDroniPort"), SAPRDroniInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SAPRDroniInterface
     */
    @WebEndpoint(name = "SAPRDroniPort")
    public SAPRDroniInterface getSAPRDroniPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.sapr.uniroma2.it/", "SAPRDroniPort"), SAPRDroniInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SAPRDRONISERVICE_EXCEPTION!= null) {
            throw SAPRDRONISERVICE_EXCEPTION;
        }
        return SAPRDRONISERVICE_WSDL_LOCATION;
    }

}
