
package it.uniroma2.sapr.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SAPRDroni", targetNamespace = "http://service.sapr.uniroma2.it/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SAPRDroni {


    /**
     * 
     * @param request
     * @return
     *     returns java.lang.Boolean
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "managerPilot", targetNamespace = "http://service.sapr.uniroma2.it/", className = "it.uniroma2.sapr.service.ManagerPilot")
    @ResponseWrapper(localName = "managerPilotResponse", targetNamespace = "http://service.sapr.uniroma2.it/", className = "it.uniroma2.sapr.service.ManagerPilotResponse")
    @Action(input = "http://service.sapr.uniroma2.it/SAPRDroni/managerPilotRequest", output = "http://service.sapr.uniroma2.it/SAPRDroni/managerPilotResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://service.sapr.uniroma2.it/SAPRDroni/managerPilot/Fault/Exception")
    })
    public Boolean managerPilot(
        @WebParam(name = "request", targetNamespace = "")
        RequestPilot request)
        throws Exception_Exception
    ;

    /**
     * 
     * @param request
     * @return
     *     returns java.lang.Boolean
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "managerSAPR", targetNamespace = "http://service.sapr.uniroma2.it/", className = "it.uniroma2.sapr.service.ManagerSAPR")
    @ResponseWrapper(localName = "managerSAPRResponse", targetNamespace = "http://service.sapr.uniroma2.it/", className = "it.uniroma2.sapr.service.ManagerSAPRResponse")
    @Action(input = "http://service.sapr.uniroma2.it/SAPRDroni/managerSAPRRequest", output = "http://service.sapr.uniroma2.it/SAPRDroni/managerSAPRResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://service.sapr.uniroma2.it/SAPRDroni/managerSAPR/Fault/Exception")
    })
    public Boolean managerSAPR(
        @WebParam(name = "request", targetNamespace = "")
        RequestSAPR request)
        throws Exception_Exception
    ;

    /**
     * 
     * @param request
     * @return
     *     returns java.lang.Boolean
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "managerDevice", targetNamespace = "http://service.sapr.uniroma2.it/", className = "it.uniroma2.sapr.service.ManagerDevice")
    @ResponseWrapper(localName = "managerDeviceResponse", targetNamespace = "http://service.sapr.uniroma2.it/", className = "it.uniroma2.sapr.service.ManagerDeviceResponse")
    @Action(input = "http://service.sapr.uniroma2.it/SAPRDroni/managerDeviceRequest", output = "http://service.sapr.uniroma2.it/SAPRDroni/managerDeviceResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://service.sapr.uniroma2.it/SAPRDroni/managerDevice/Fault/Exception")
    })
    public Boolean managerDevice(
        @WebParam(name = "request", targetNamespace = "")
        RequestDevice request)
        throws Exception_Exception
    ;

    /**
     * 
     * @param request
     * @return
     *     returns java.lang.Boolean
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "managerNote", targetNamespace = "http://service.sapr.uniroma2.it/", className = "it.uniroma2.sapr.service.ManagerNote")
    @ResponseWrapper(localName = "managerNoteResponse", targetNamespace = "http://service.sapr.uniroma2.it/", className = "it.uniroma2.sapr.service.ManagerNoteResponse")
    @Action(input = "http://service.sapr.uniroma2.it/SAPRDroni/managerNoteRequest", output = "http://service.sapr.uniroma2.it/SAPRDroni/managerNoteResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://service.sapr.uniroma2.it/SAPRDroni/managerNote/Fault/Exception")
    })
    public Boolean managerNote(
        @WebParam(name = "request", targetNamespace = "")
        RequestNote request)
        throws Exception_Exception
    ;

    /**
     * 
     * @param request
     * @return
     *     returns java.lang.Boolean
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "managerFlightPlan", targetNamespace = "http://service.sapr.uniroma2.it/", className = "it.uniroma2.sapr.service.ManagerFlightPlan")
    @ResponseWrapper(localName = "managerFlightPlanResponse", targetNamespace = "http://service.sapr.uniroma2.it/", className = "it.uniroma2.sapr.service.ManagerFlightPlanResponse")
    @Action(input = "http://service.sapr.uniroma2.it/SAPRDroni/managerFlightPlanRequest", output = "http://service.sapr.uniroma2.it/SAPRDroni/managerFlightPlanResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://service.sapr.uniroma2.it/SAPRDroni/managerFlightPlan/Fault/Exception")
    })
    public Boolean managerFlightPlan(
        @WebParam(name = "request", targetNamespace = "")
        RequestFlightPlan request)
        throws Exception_Exception
    ;

}
